/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4f6263fd-34f2-44c9-9e4c-34333f7abeff",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6rviebTkq",
    "aws_user_pools_web_client_id": "6nfe54d0e4kspdioku0g7tfkru",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jcnst5s3ffgofkebu4pm6zumjy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-p6ct3ftgbrertd2mvj43issvfq"
};


export default awsmobile;
